### ISSUE TITLE
[Engineering] Toggling between `Projects` and `Post a Job` takes too long

### ISSUE THREAD

**Issue by samgompers** [workhard-finance/frontend-v1#10]
**Work Page**

**Issue**
When toggling between the `Projects` tab and the `Post a Job` tab, the browser hangs.

**Suggestion**
Speed up toggle time or fix this issue

**Comment by 0xMayflower** [comment]
Fixed by https://github.com/workhard-finance/frontend-v1/commit/1fa91294a55bae0decc2a598ef745fb9d49b5419
