### ISSUE TITLE
Navbar tokens

### ISSUE THREAD

**Issue by 0xMayflower** [workhard-finance/frontend-v1#33]
1. They should display their own symbols.
Please see Dashboard.tsx
![image](https://user-images.githubusercontent.com/78292562/121782554-fd71ae80-cbe4-11eb-818a-367178fc160f.png)

2. Would you please use this function for the balance display?
https://github.com/workhard-finance/frontend-v1/blob/9f867c1c5698c9b3d9be65d4fa07ce1d626d3071/src/utils/utils.ts#L146-L148

**Comment by 0xMayflower** [comment]
We may have to hold the context and provide it to the children elements using Context / Provider API.
It. It is reloading token balances when the navbar's updated.

![image](https://i.imgur.com/y2Ae3z5.gif)

**Comment by zzorum** [comment]
@0xMayflower please check PR #34

**Comment by 0xMayflower** [comment]
closed by #33
